# Generated by Django 5.1.5 on 2025-04-12 16:47

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('storage_location', models.CharField(max_length=100)),
                ('condition', models.CharField(choices=[('excellent', 'Excellent'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor')], default='good', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='SafetyRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('general', 'General Safety'), ('equipment', 'Equipment Use'), ('emergency', 'Emergency Procedures')], max_length=20)),
                ('reference', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SkillAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(choices=[('throw', 'Throwing'), ('catch', 'Catching'), ('run', 'Running'), ('jump', 'Jumping'), ('strike', 'Striking')], max_length=20)),
                ('score', models.IntegerField(choices=[(1, 'Beginning'), (2, 'Developing'), (3, 'Proficient'), (4, 'Advanced')])),
                ('notes', models.TextField(blank=True)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('grade_level', models.IntegerField(choices=[(1, 'Grade 1'), (2, 'Grade 2'), (3, 'Grade 3'), (4, 'Grade 4'), (5, 'Grade 5'), (6, 'Grade 6')])),
            ],
        ),
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['-created_at'], 'permissions': [('special_status', 'Can read all lessons')]},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='activity',
            name='grade_level',
            field=models.IntegerField(choices=[(1, 'Grade 1'), (2, 'Grade 2'), (3, 'Grade 3'), (4, 'Grade 4'), (5, 'Grade 5'), (6, 'Grade 6')], default=1),
        ),
        migrations.AddField(
            model_name='activity',
            name='objectives',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='lesson',
            name='activity_type',
            field=models.CharField(choices=[('warmup', 'Warm-up'), ('main', 'Main Activity'), ('game', 'Game'), ('skill', 'Skill Development'), ('cool', 'Cool-down')], default='main', max_length=20),
        ),
        migrations.AddField(
            model_name='lesson',
            name='duration',
            field=models.PositiveIntegerField(default=30, help_text='Duration in minutes'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='grade_level',
            field=models.IntegerField(choices=[(1, 'Grade 1'), (2, 'Grade 2'), (3, 'Grade 3'), (4, 'Grade 4'), (5, 'Grade 5'), (6, 'Grade 6')], default=1),
        ),
        migrations.AddField(
            model_name='lesson',
            name='objectives',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), blank=True, default=list, help_text='Learning objectives', size=None),
        ),
        migrations.AlterField(
            model_name='activity',
            name='duration',
            field=models.PositiveIntegerField(help_text='Duration in minutes'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='intensity_level',
            field=models.CharField(choices=[('low', 'Low'), ('moderate', 'Moderate'), ('high', 'High')], max_length=20),
        ),
        migrations.AlterField(
            model_name='activity',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='lessons.lesson'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='review',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='activity',
            name='equipment_needed',
            field=models.ManyToManyField(blank=True, to='lessons.equipment'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='equipment_needed',
            field=models.ManyToManyField(blank=True, to='lessons.equipment'),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['grade_level'], name='grade_level_index'),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['activity_type'], name='activity_type_index'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment', to='lessons.school'),
        ),
        migrations.AddField(
            model_name='skillassessment',
            name='assessed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='student',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lessons.school'),
        ),
        migrations.AddField(
            model_name='skillassessment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills_assessed', to='lessons.student'),
        ),
        migrations.AlterUniqueTogether(
            name='skillassessment',
            unique_together={('student', 'skill', 'date')},
        ),
    ]
