# Generated by Django 5.1.5 on 2025-04-12 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_equipment_safetyrule_school_skillassessment_student_and_more'),
    ]

    operations = [
    ]
