# Generated by Django 5.1.5 on 2025-05-25 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_delete_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='available',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='lesson',
            name='shareable',
            field=models.BooleanField(default=False, help_text='Allow other teachers to view'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
