# Generated by Django 5.1.5 on 2025-02-09 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0003_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='covers/'),
        ),
    ]
