# Generated by Django 5.1.5 on 2025-04-14 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0004_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='age_group',
            field=models.CharField(blank=True, choices=[('child', 'Child (6-12)'), ('teen', 'Teen (13-19)'), ('adult', 'Adult (20+)')], max_length=20, null=True),
        ),
    ]
