# Generated by Django 5.1.5 on 2025-02-10 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0004_lesson_cover'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'permissions': [('special_status', 'Can read all books')]},
        ),
    ]
