# Generated by Django 5.1.5 on 2025-04-14 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0005_lesson_age_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='equipment_needed',
            field=models.ManyToManyField(blank=True, related_name='lessons', to='lessons.equipment'),
        ),
    ]
