# Generated by Django 5.1.5 on 2025-02-12 16:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0005_alter_lesson_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['id'], name='id_index'),
        ),
    ]
