# Generated by Django 5.1.5 on 2025-04-15 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0006_alter_lesson_equipment_needed'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='activity_type',
            field=models.CharField(choices=[('warmup', 'Warm-up'), ('main', 'Main Activity'), ('cool', 'Cool-down'), ('game', 'Game'), ('skill', 'Skill Development')], default='main', max_length=20),
        ),
    ]
