# Generated by Django 5.1.5 on 2025-04-21 17:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0008_safetyrule_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='safetyrule',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='safetyrule',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
