# Generated by Django 5.1.5 on 2025-04-21 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0009_safetyrule_created_at_safetyrule_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='safetyrule',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
