# Generated by Django 5.1.5 on 2025-04-30 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0011_equipment_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurriculumDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.IntegerField(choices=[(1, 'Grade 1'), (2, 'Grade 2'), (3, 'Grade 3'), (4, 'Grade 4'), (5, 'Grade 5')])),
                ('document_type', models.CharField(choices=[('session_sheet', 'Session Sheet'), ('annual_program', 'Annual Program'), ('annual_distribution', 'Annual Distribution'), ('trimester_clip', 'Trimester Clip'), ('curriculum', 'Physical Education Curriculum')], max_length=20)),
                ('trimester', models.IntegerField(blank=True, choices=[(1, 'First'), (2, 'Second'), (3, 'Third')], null=True)),
                ('academic_year', models.CharField(max_length=9)),
                ('title', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='curriculum_documents/')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['grade', 'document_type', 'academic_year'],
            },
        ),
        migrations.AlterField(
            model_name='activity',
            name='grade_level',
            field=models.IntegerField(choices=[(1, 'Grade 1'), (2, 'Grade 2'), (3, 'Grade 3'), (4, 'Grade 4'), (5, 'Grade 5')], default=1),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='grade_level',
            field=models.IntegerField(choices=[(1, 'Grade 1'), (2, 'Grade 2'), (3, 'Grade 3'), (4, 'Grade 4'), (5, 'Grade 5')], default=1),
        ),
        migrations.AlterField(
            model_name='student',
            name='grade_level',
            field=models.IntegerField(choices=[(1, 'Grade 1'), (2, 'Grade 2'), (3, 'Grade 3'), (4, 'Grade 4'), (5, 'Grade 5')]),
        ),
    ]
