# Generated by Django 5.1.5 on 2025-04-30 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0012_curriculumdocument_alter_activity_grade_level_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='curriculumdocument',
            options={'ordering': ['grade', 'document_type', '-version']},
        ),
        migrations.AddField(
            model_name='curriculumdocument',
            name='changelog',
            field=models.TextField(blank=True, help_text='Describe changes from previous version'),
        ),
        migrations.AddField(
            model_name='curriculumdocument',
            name='is_current',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='curriculumdocument',
            name='previous_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_versions', to='lessons.curriculumdocument'),
        ),
        migrations.AddField(
            model_name='curriculumdocument',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterUniqueTogether(
            name='curriculumdocument',
            unique_together={('grade', 'document_type', 'academic_year', 'version')},
        ),
    ]
